# Google Analytics tracking ID.
googleAnalytics: "G-3J0N2M6TXC"
# Details are also stored in layouts/partials/header.html for this to work. Commented out until I can get a handle on the cookie situation!

# baseURL: https://bttech.co.uk Removed for the moment until the DNS verification is up and running for the domain
baseURL: https://www.bttech.co.uk

languageCode: en-us
title: "Ben's Blog"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/bttechcouk/bttechcouk.github.io

  # specify whether you want to write some blog posts or not
  enableBlogPost: false # set this to true when ready to go with the blogs!

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false
    
  background: "images/default-background-2.jpg"
